# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/lemon-zf"
  #weibo: ""
  rss: /atom.xml
  # facebook: "/"
  # google: "/"
  # twitter: "/"
  # linkedin: "/"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous

favicon: /assets/favicon.ico

avatar: /assets/images/lemon.png
share: true
duoshuo: "it-lemon"
tagcloud: true

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我和谁都不争，和谁争我都不屑；我爱coding，其次就是nature；我双手烤着生命之火取暖；火fade了，我也准备go了。